os:
  - linux
  - osx

# JRuby and Ruby 1.8.7 isn't working on the new default distribution
dist: trusty

language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - jruby-9.1.7.0

matrix:
  exclude:
      # Ruby 2.3.x is currently broken on TravisCI for OSX and is no longer a supported Ruby version, anyway.
    - rvm: 2.3.8
      os: osx

gemfile:
  - testing/gemfiles/cql1.gemfile
  - testing/gemfiles/cuke_modeler0.gemfile
  - testing/gemfiles/cuke_modeler1.gemfile
  - testing/gemfiles/cuke_modeler2.gemfile
  - testing/gemfiles/cuke_modeler3.gemfile
  - testing/gemfiles/rake10.gemfile
  - testing/gemfiles/rake11.gemfile
  - testing/gemfiles/rake12.gemfile
  - testing/gemfiles/rake13.gemfile
  - testing/gemfiles/thor0.gemfile
  - testing/gemfiles/thor1.gemfile

before_install:
  - gem install bundler -v '< 2'

script: bundle exec rake cuke_cataloger:ci_build
