version: '1.0.{build}'

environment:
  matrix:

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cql1.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cql1.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cql1.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cql1.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler0.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler0.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler0.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler0.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler3.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler3.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler3.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler3.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/rake10.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/rake10.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/rake10.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/rake10.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/rake11.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/rake11.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/rake11.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/rake11.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/rake12.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/rake12.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/rake12.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/rake12.gemfile

    # Rake 13.x requires Ruby 2.2 or higher
    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/rake13.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/rake13.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/rake13.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/rake13.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/thor0.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/thor0.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/thor0.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/thor0.gemfile

    # Thor 1.x requires Ruby 2.0 or higher
    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/thor1.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/thor1.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/thor1.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/thor1.gemfile


# Allow Windows builds to use CRLF as expected by linting tools, etc.
init:
  - git config --global core.autocrlf true


install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake cql:ci_build
