ENV['CUKE_CATALOGER_REPORT_FOLDER'] ||= "#{__dir__}/reports"
ENV['CUKE_CATALOGER_RSPEC_REPORT_NAME'] ||= 'rspec_report'
ENV['CUKE_CATALOGER_RSPEC_REPORT_HTML_FILE'] ||= "#{ENV['CUKE_CATALOGER_RSPEC_REPORT_NAME']}.html"
ENV['CUKE_CATALOGER_CUCUMBER_REPORT_NAME'] ||= 'cucumber_report'
ENV['CUKE_CATALOGER_CUCUMBER_REPORT_HTML_FILE'] ||= "#{ENV['CUKE_CATALOGER_CUCUMBER_REPORT_NAME']}.html"
