require 'simplecov'
require 'securerandom'

SimpleCov.start do
  root File.dirname(__FILE__) + '/../..'

  # Every test process will need its own unique name or else they will override each others' coverage data
  command_name("cuke_cataloger-fixtures-#{SecureRandom.uuid}")

  add_filter '/testing/'

  merge_timeout 300
end


require 'cuke_cataloger'
